/* File: christmas/script.js
   Purpose: Frontend logic for offers.solisgreenindia.in/christmas/
   Generated by request (GTM events: enabled).
   Notes:
     - Expects server endpoints at /api/reveal and /api/claim (Vercel functions recommended).
     - Includes GTM dataLayer pushes for reveal_click, reservation_created, reservation_expired,
       claim_submitted, and claim_failed.
     - Has a demo fallback mode when APIs are unavailable (ALLOW_FALLBACK = true).
*/

/* eslint-disable no-console */
(function () {
  // -------------------------
  // Configuration
  // -------------------------
  const REVEAL_API = "/api/reveal"; // server endpoint that creates a reservation
  const CLAIM_API = "/api/claim"; // server endpoint to submit a claim
  const DEFAULT_TTL_SECONDS = 600; // fallback TTL (10 minutes)
  const ALLOW_FALLBACK = true; // if true and reveal API is missing, demo reservation is created
  const RESERVATION_TOLERANCE_MS = 1000; // small tolerance for expiry checks

  // GTM (dataLayer) - ensure global dataLayer exists
  window.dataLayer = window.dataLayer || [];

  // -------------------------
  // DOM elements
  // -------------------------
  const el = {
    revealBtn: document.getElementById("revealBtn"),
    revealResult: document.getElementById("revealResult"),
    revealMessage: document.getElementById("revealMessage"),
    countdown: document.getElementById("countdown"),
    revealErrors: document.getElementById("revealErrors"),

    claimForm: document.getElementById("claimForm"),
    submitBtn: document.getElementById("submitBtn"),
    revealTokenInput: document.getElementById("revealToken"),
    formFeedback: document.getElementById("formFeedback"),
    liveRegion: document.getElementById("liveRegion"),
  };

  // -------------------------
  // State
  // -------------------------
  let reservation = null; // { token, prize, expiresAt (ms) }
  let countdownTimer = null;

  // Expose for debugging/admin console
  window.christmasOffer = {
    getReservation: () => reservation,
    clearReservation: () => {
      if (countdownTimer) clearInterval(countdownTimer);
      reservation = null;
      el.revealTokenInput.value = "";
      el.revealResult.style.display = "none";
      el.revealErrors.innerHTML = "";
      el.submitBtn.disabled = true;
      el.revealBtn.disabled = false;
      el.revealBtn.textContent = "🎁 Unlock Your Gift";
      pushEvent("reservation_cleared", {});
    },
  };

  // -------------------------
  // Helpers
  // -------------------------
  function nowMs() {
    return Date.now();
  }

  function formatSeconds(s) {
    s = Math.max(0, Math.floor(s));
    const m = Math.floor(s / 60).toString().padStart(2, "0");
    const sec = (s % 60).toString().padStart(2, "0");
    return `${m}:${sec}`;
  }

  function announce(msg) {
    if (el.liveRegion) {
      el.liveRegion.textContent = msg;
      setTimeout(() => {
        el.liveRegion.textContent = "";
      }, 1600);
    }
  }

  // Simple phone validation: Indian mobiles starting with 6-9 and 10 digits
  function validatePhone(v) {
    if (!v) return false;
    return /^[6-9]\d{9}$/.test(v.trim());
  }
  // KSEB consumer: allow alnum + hyphen; fallback generic validation
  function validateKsebConsumer(v) {
    if (!v) return false;
    return /^[A-Za-z0-9\-]{5,20}$/.test(v.trim());
  }

  function pushEvent(eventName, data) {
    try {
      window.dataLayer = window.dataLayer || [];
      window.dataLayer.push(Object.assign({ event: eventName }, data || {}));
      // For debugging:
      // console.log('dataLayer.push', eventName, data);
    } catch (e) {
      // ignore
    }
  }

  // -------------------------
  // Countdown / expiry handling
  // -------------------------
  function startCountdown(expiresAtMs) {
    if (countdownTimer) clearInterval(countdownTimer);

    function tick() {
      const remainingSec = Math.ceil((expiresAtMs - nowMs()) / 1000);
      el.countdown.textContent = formatSeconds(remainingSec);
      if (remainingSec <= 0) {
        clearInterval(countdownTimer);
        onReservationExpired();
      }
    }

    tick();
    countdownTimer = setInterval(tick, 1000);
  }

  function onReservationExpired() {
    // mark reservation expired locally
    if (reservation) {
      pushEvent("reservation_expired", {
        revealToken: reservation.token,
        prize: reservation.prize,
      });
    }
    reservation = null;
    el.revealResult.style.display = "none";
    el.revealErrors.innerHTML =
      '<div class="error">⏳ Your reservation expired. Please click "Unlock Your Gift" again to try.</div>';
    el.revealBtn.disabled = false;
    el.revealBtn.textContent = "🎁 Unlock Your Gift";
    el.revealTokenInput.value = "";
    el.submitBtn.disabled = true;
    announce("Reservation expired");
  }

  // -------------------------
  // Reveal -> call server to create reservation
  // -------------------------
  async function handleReveal() {
    el.revealErrors.innerHTML = "";
    el.revealBtn.disabled = true;
    el.revealBtn.textContent = "🎅 Checking your gift...";

    // push click event
    pushEvent("reveal_click", { campaign: "christmas" });

    // Call server
    try {
      const resp = await fetch(REVEAL_API, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ campaign: "christmas" }),
      });

      if (!resp.ok) throw new Error("Server returned " + resp.status);

      const data = await resp.json();
      // expected: { prize:5000, revealToken:"...", expiresIn:600 }
      const prize = data.prize ?? 5000;
      const token = data.revealToken ?? data.token ?? null;
      const ttl = parseInt(data.expiresIn ?? data.ttl ?? DEFAULT_TTL_SECONDS, 10);

      if (!token) throw new Error("Missing reveal token from server.");

      reservation = {
        token,
        prize,
        expiresAt: nowMs() + ttl * 1000,
      };

      el.revealTokenInput.value = token;
      el.revealMessage.textContent = `🎉 You have unlocked ₹${prize.toLocaleString()} — fill the form to claim within the time limit.`;
      el.revealResult.style.display = "block";
      el.revealBtn.textContent = "🎁 Gift Reserved";
      startCountdown(reservation.expiresAt);
      el.submitBtn.disabled = false;
      announce("Gift reserved. Form is available.");

      // push reservation created event
      pushEvent("reservation_created", {
        revealToken: token,
        prize,
        expiresIn: ttl,
        campaign: "christmas",
      });
    } catch (err) {
      // API failed or not available
      console.warn("Reveal API failed:", err);
      if (ALLOW_FALLBACK) {
        const demoToken = "demo-" + Math.random().toString(36).slice(2, 12);
        reservation = {
          token: demoToken,
          prize: 5000,
          expiresAt: nowMs() + DEFAULT_TTL_SECONDS * 1000,
        };
        el.revealTokenInput.value = demoToken;
        el.revealMessage.textContent = `🎉 Demo: You have unlocked ₹${reservation.prize.toLocaleString()}. This is a local demo reservation — integrate server APIs for production.`;
        el.revealResult.style.display = "block";
        el.revealBtn.textContent = "🎁 Gift Reserved (demo)";
        startCountdown(reservation.expiresAt);
        el.submitBtn.disabled = false;
        announce("Demo gift reserved. Form is available.");
        // push reservation created (demo)
        pushEvent("reservation_created", {
          revealToken: demoToken,
          prize: reservation.prize,
          expiresIn: DEFAULT_TTL_SECONDS,
          campaign: "christmas",
          demo: true,
        });
      } else {
        el.revealErrors.innerHTML =
          '<div class="error">Unable to reserve gift right now. Please try again later.</div>';
        el.revealBtn.disabled = false;
        el.revealBtn.textContent = "🎁 Unlock Your Gift";
      }
    }
  }

  // -------------------------
  // Claim -> submit form to server
  // -------------------------
  async function handleClaimSubmit(e) {
    e.preventDefault();
    el.formFeedback.textContent = "";

    // ensure reservation exists and not expired
    if (!reservation) {
      el.formFeedback.innerHTML = '<div class="error">You need to reserve a slot first — click "Unlock Your Gift".</div>';
      return;
    }
    if (nowMs() > reservation.expiresAt - RESERVATION_TOLERANCE_MS) {
      onReservationExpired();
      return;
    }

    // collect data
    const payload = {
      revealToken: el.revealTokenInput.value,
      name: (document.getElementById("name") || {}).value?.trim() || "",
      phone: (document.getElementById("phone") || {}).value?.trim() || "",
      ksebConsumer: (document.getElementById("ksebConsumer") || {}).value?.trim() || "",
      ksebPhone: (document.getElementById("ksebPhone") || {}).value?.trim() || "",
      location: (document.getElementById("location") || {}).value?.trim() || "",
      campaign: "christmas",
    };

    // client-side validations
    if (!payload.name) {
      el.formFeedback.innerHTML = '<div class="error">Please enter your name.</div>';
      return;
    }
    if (!validatePhone(payload.phone)) {
      el.formFeedback.innerHTML = '<div class="error">Enter a valid 10-digit mobile number (starts with 6-9).</div>';
      return;
    }
    if (!validateKsebConsumer(payload.ksebConsumer)) {
      el.formFeedback.innerHTML = '<div class="error">Enter a valid KSEB Consumer Number (alphanumeric).</div>';
      return;
    }
    if (!validatePhone(payload.ksebPhone)) {
      el.formFeedback.innerHTML = '<div class="error">Enter a valid KSEB registered phone (10 digits).</div>';
      return;
    }
    if (!payload.location) {
      el.formFeedback.innerHTML = '<div class="error">Please enter your location (town / pincode).</div>';
      return;
    }
    const consent = document.getElementById("consent");
    if (!consent || !consent.checked) {
      el.formFeedback.innerHTML = '<div class="error">You must consent to be contacted about this offer.</div>';
      return;
    }

    // disable submit while sending
    el.submitBtn.disabled = true;
    el.submitBtn.textContent = "⏳ Submitting...";

    // push event: claim_attempt
    pushEvent("claim_attempt", {
      revealToken: payload.revealToken,
      campaign: "christmas",
    });

    try {
      const resp = await fetch(CLAIM_API, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!resp.ok) {
        let msg = "Server error. Please try again.";
        try {
          const j = await resp.json();
          if (j?.error) msg = j.error;
        } catch (e) {
          // ignore parse error
        }
        throw new Error(msg);
      }

      const data = await resp.json();
      // Expected: { success:true, message:"...", claimId: "..." }
      el.formFeedback.innerHTML = `<div class="success">✅ ${data.message ?? "Claim submitted. We will contact you within 24 hours."}</div>`;
      announce("Claim submitted successfully.");

      // Clear local reservation so that slot cannot be reused
      reservation = null;
      el.revealTokenInput.value = "";
      el.revealResult.style.display = "none";
      if (countdownTimer) clearInterval(countdownTimer);
      el.revealBtn.disabled = false;
      el.revealBtn.textContent = "🎁 Unlock Your Gift";
      el.claimForm.reset();

      // push GTM event for success
      pushEvent("claim_submitted", {
        revealToken: payload.revealToken,
        claimId: data.claimId ?? null,
        prize: reservation?.prize ?? null,
        campaign: "christmas",
      });
    } catch (err) {
      // error handling
      el.formFeedback.innerHTML = `<div class="error">${err.message}</div>`;
      announce("There was an error submitting your claim.");
      // push GTM failure
      pushEvent("claim_failed", {
        revealToken: payload.revealToken,
        error: err.message,
        campaign: "christmas",
      });
      el.submitBtn.disabled = false;
      el.submitBtn.textContent = "Claim ₹5,000 & Get Free Consultation";
    }
  }

  // -------------------------
  // Init bindings
  // -------------------------
  function init() {
    if (!el.revealBtn || !el.claimForm) {
      console.warn("Christmas script: required DOM elements missing.");
      return;
    }

    el.revealBtn.addEventListener("click", handleReveal);
    el.claimForm.addEventListener("submit", handleClaimSubmit);

    // Make submit enable/disable reactive to revealToken input changes
    const observer = new MutationObserver(() => {
      el.submitBtn.disabled = !el.revealTokenInput.value;
    });
    observer.observe(el.revealTokenInput, { attributes: true, childList: false, subtree: false });

    // Initial state
    el.submitBtn.disabled = true;
    // year filler if present
    const yearEl = document.getElementById("year");
    if (yearEl) yearEl.textContent = new Date().getFullYear();

    // accessibility announcement
    announce("Christmas offer loaded");
  }

  // Run init on DOMContentLoaded if not already loaded
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
